---
title: Error Handling
---

Whenever you execute a GraphQL operation, two high-level types of errors can occur:

- **Execution errors**: a GraphQL response wasn't received because an error occurred during request execution. This could be a networking error (SSL, socket, HTTP), a client-side error (response parsing failure, invalid cache data), or other execution failures. When an execution error occurs, no data is returned.
- **GraphQL errors**: a GraphQL response is received, and it contains a non-empty [`errors`](https://spec.graphql.org/draft/#sec-Errors) field. This means the server wasn't able to completely process the query. The response might include partial data if the server was able to process some of the query.

## Execution errors

Execution errors are thrown as exceptions that you can catch in a `do/catch` block. These errors indicate a fatal error and terminate execution of the operation.

```swift
do {
  let response = try await apollo.fetch(query: HeroNameQuery())
  // Handle successful response
  print(response.data?.hero?.name)
} catch {
  // Execution error (networking, parsing, cache, etc.)
  print("Error executing operation: \(error)")
}
```

### Causes

Possible causes of an execution error include (but are not limited to):

**Networking errors:**
* The app is offline or doesn't have access to the network.
* A DNS error occurred, making it impossible to look up the host.
* An SSL error occurred (e.g., the server certificate isn't trusted).
* The connection was closed.
* The server responded with a non-successful HTTP code.

**Client-side errors:**
* The response JSON could not be parsed into a valid response model for the operation.
* File I/O failed while reading cache data.
* Invalid cache data was encountered.

## GraphQL errors

Because a response with GraphQL errors might still contain data, an execution error is not thrown. Instead, a successful response is returned containing a [`GraphQLResponse`](https://www.apollographql.com/docs/ios/docc/documentation/apollo/graphqlresponse) whose `errors` field contains the errors that occurred.

For example, the following query uses an invalid `id` to look up a `Person`:

```graphql
query FilmAndPersonQuery {
  film(id: "ZmlsbXM6M") {
    title
  }
  person(id: "badId") {
    name
  }
}
```

The server will send the following response:

```json
{
  "data": {
    "film": {
      "title": "A New Hope"
    },
    "person": null
  },
  "errors": [
    {
      "message": "No entry in local cache for https://swapi.dev/api/people/mï¿½H/",
      "locations": [
        {
          "line": 35,
          "column": 3
        }
      ],
      "path": [
        "person"
      ]
    }
  ]
}
```

Note that while there are errors, the query successfully returned the title of the film: `A New Hope`. In general, any error while executing an operation [bubbles up](https://spec.graphql.org/draft/#sec-Errors) to the next nullable field. In this case `data?.person` is `nil`. In the worst case, `GraphQLResponse.data` may be `nil` if everything else is non-nullable.

Apollo iOS gives you access to both the `data` and the `errors` in the [`GraphQLResponse`](https://www.apollographql.com/docs/ios/docc/documentation/apollo/graphqlresponse):

```swift
do {
  let response = try await apollo.fetch(query: FilmAndPersonQuery())

  if let errors = response.errors {
    // GraphQL errors - handle these as needed
    print("GraphQL errors: \(errors)")
  }

  let film = response.data?.film // Exists
  let person = response.data?.person // nil

} catch {
  // Execution error (networking, parsing, cache, etc.)
  print("Error executing operation: \(error)")
}
```

GraphQL errors are returned as type-safe [`GraphQLError`](https://www.apollographql.com/docs/ios/docc/documentation/apollo/graphqlerror) values. These values are parsed from the response as described in the section on [response format errors in the GraphQL specification](https://spec.graphql.org/October2021/#sec-Errors).
